
spring:
  devtools:
    livereload:
      enable: true
  output:
    ansi:
      enabled: detect
  datasource:
    url: jdbc:postgresql://20.214.108.168:15432/testdb
    username: testuser
    password: testuser
  jpa:
    properties:
      hibernate:
        format_sql: true
        sql_show: true
        use_sql_comments: true
        ddl-auto: none
    generate-ddl: false
    show-sql: true

#cors setting
cors:
  origins:
    http://localhost:8080,
    http://20.214.108.168:8080,
    https://20.214.108.168:8080,
    http://www.dalgom.app,
    https://www.dalgom.app,
    http://dalgom.app,
    https://dalgom.app,


# Log
logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

  level.org.hibernate.type.descriptor.sql.BasicBinder: trace
  level.org.apache.commons.beanutils: error
  file:
    name: ./logs/login-local.log